

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devops-chatbot-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-chatbot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatbot123}
      POSTGRES_DB: ${POSTGRES_DB:-devops_chatbot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-chatbot} -d ${POSTGRES_DB:-devops_chatbot}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-search-mcp:
    build:
      context: ./web-search-mcp
      dockerfile: Dockerfile
    container_name: web-search-mcp
    environment:
      MAX_CONTENT_LENGTH: "15000"
      DEFAULT_TIMEOUT: "6000"
      MAX_BROWSERS: "2"
      BROWSER_HEADLESS: "true"
      ENABLE_RELEVANCE_CHECKING: "true"
      RELEVANCE_THRESHOLD: "0.3"
    volumes:
      - /dev/shm:/dev/shm  # Shared memory for browsers
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "wget --quiet --spider http://127.0.0.1:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops-chatbot-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-chatbot}:${POSTGRES_PASSWORD:-chatbot123}@postgres:5432/${POSTGRES_DB:-devops_chatbot}
      POSTGRES_USER: ${POSTGRES_USER:-chatbot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatbot123}
      POSTGRES_DB: ${POSTGRES_DB:-devops_chatbot}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY:-}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2:-false}
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT:-devops-chatbot}
      MCP_SERVER_URL: http://web-search-mcp:3000
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
      - ./backend/main.py:/app/main.py
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      web-search-mcp:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: devops-chatbot-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
